events {}

http {
  server {
    listen 80;

    # Route requests starting with /api/location to the Location Service
    location /api/location {
      # The hostname 'location-service' matches the service name in docker-compose
      proxy_pass http://location-service:3001/location;
    }

    # Route requests starting with /api/weather to the Weather Service
    location /api/weather {
      proxy_pass http://weather-service:3002/weather;
    }
  }
}